services:
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sheetmusic
      - POSTGRES_USER=sheetmusic
      - POSTGRES_PASSWORD=sheetmusic
    # ports:
    #   - "5433:5432"  # No exponer puerto, solo acceso interno
    networks:
      - sheetmusic-network

  # Servicio del backend (Django)
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput --clear || true &&
             gunicorn --bind 0.0.0.0:8000 sheetmusic_api.wsgi:application"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=sheetmusic_api.settings
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=sheetmusic
      - SQL_USER=sheetmusic
      - SQL_PASSWORD=sheetmusic
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    networks:
      - sheetmusic-network

  # Servicio del frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build/static:/usr/share/nginx/html/static
    depends_on:
      - backend
    networks:
      - sheetmusic-network
    restart: unless-stopped

# Volúmenes para persistencia de datos
volumes:
  postgres_data:
  static_volume:
  media_volume:

# Red para la comunicación entre servicios
networks:
  sheetmusic-network:
    driver: bridge
